#pragma once
#include "CoreMinimal.h"
#include "EGeneralBattleEvent.generated.h"

UENUM(BlueprintType)
enum class EGeneralBattleEvent : uint8 {
    None UMETA(DisplayName = "No Event Selected"),
    PreStart_1P UMETA(DisplayName = "On Pre-Round Start (1P)"),
    PreStart_2P UMETA(DisplayName = "On Pre-Round Start (2P)"),
    PreStart_Fate UMETA(DisplayName = "On Pre-Round Start (Fate)"),
    FIGHT UMETA(DisplayName = "On Fight"),
    FIGHT_Fate UMETA(DisplayName = "On Fight Fate"),
    FIGHT_Mid UMETA(DisplayName = "On Fight Mid"),
    FIGHT_Last UMETA(DisplayName = "On Fight Last"),
    BattleFinish UMETA(DisplayName = "On Finished Battle"),
    BattleFinish_Last UMETA(DisplayName = "On Last Finished Battle"),
    Win UMETA(DisplayName = "On Win"),
    WallHit UMETA(DisplayName = "On Wall Hit"),
    WallHitS UMETA(DisplayName = "On Strong Wall Hit"),
    BigDamage UMETA(DisplayName = "On Big Damage"),
    RageArts UMETA(DisplayName = "On Rage Art"),
    SuperSlow UMETA(DisplayName = "On Super Slow Motion"),
    ZoneStart UMETA(DisplayName = "On Heat Start"),
    ZoneEnd UMETA(DisplayName = "On Heat End"),
    ZoneEndEffect UMETA(DisplayName = "On Heat Effect End"),
    DevilEndEffect UMETA(DisplayName = "On Devil Effect End"),
    NoticeStageDestruction UMETA(DisplayName = "On NoticeStageDestruction"),
    FloorBreak0 UMETA(DisplayName = "On First Floor Break"),
    FloorBreak1 UMETA(DisplayName = "On Second Floor Break"),
    FloorBreak2 UMETA(DisplayName = "On Third Floor Break"),
    FloorBreak3 UMETA(DisplayName = "On Fourth Floor Break"),
    FloorBreak4 UMETA(DisplayName = "On Fifth Floor Break"),
    ROUNDN UMETA(Hidden),
    ZoneBegin UMETA(DisplayName = "On ZoneBegin"),
    FloorHitS UMETA(DisplayName = "On Special Floor Hit"),
    StageUniq0 UMETA(DisplayName = "On First Unique Stage Interaction"),
    StageUniq1 UMETA(DisplayName = "On Second Unique Stage Interaction"),
    StageUniq2 UMETA(DisplayName = "On Third Unique Stage Interaction"),
    ROUND1 UMETA(DisplayName = "On First Round"),
    ROUND_OTHER UMETA(Hidden),
    WallBreak UMETA(DisplayName = "On Wall Break"),
    FightOnStageDestruction UMETA(DisplayName = "On FightOnStageDestruction"),
    ROUND_ODD UMETA(DisplayName = "On Odd Round Count"),
    ROUND_EVEN UMETA(DisplayName = "On Even Round Count"),
    ROUND1_Practice UMETA(DisplayName = "On Practice"),
    DemoSkip UMETA(DisplayName = "On DemoSkip"),
    Max UMETA(Hidden),
    ROUNDN_2 = 128 UMETA(DisplayName = "On Second Round"),
    ROUNDN_3 UMETA(DisplayName = "On Third Round"),
    ROUNDN_4 UMETA(DisplayName = "On Fourth Round"),
    ROUNDN_5 UMETA(DisplayName = "On Fifth Round"),
    ROUNDN_6 UMETA(DisplayName = "On Sixth Round"),
    ROUNDN_7 UMETA(DisplayName = "On Seventh Round"),
    ROUNDN_8 UMETA(DisplayName = "On Eigth Round"),
    ROUNDN_9 UMETA(DisplayName = "On Ninth Roumd"),
    ROUND_START_2 UMETA(DisplayName = "On Start Of Second Round"),
    ROUND_START_3 UMETA(DisplayName = "On Start Of Third Round"),
    ROUND_START_4 UMETA(DisplayName = "On Start Of Fourth Round"),
    ROUND_START_5 UMETA(DisplayName = "On Start Of Fifth Round"),
    ROUND_START_6 UMETA(DisplayName = "On Start Of Sixth Round"),
    ROUND_START_7 UMETA(DisplayName = "On Start Of Seventh Round"),
    ROUND_START_8 UMETA(DisplayName = "On Start Of Eigth Round"),
    ROUND_START_9 UMETA(DisplayName = "On Start Of Ninth Round"),
};

